#KeShiHua项目的设置文件，配置。
"""
Django settings for KeShiHua project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(fksie^4=h9dj6u#nq326p&qz$bsv@5@e78n2p2kt8d$#drxd)' #密钥

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'KeShiHua.apps.KeShiHuaConfig',
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 这是allauth的依赖包，必须在app和allauth之前
    'django.contrib.sites',
    # 用户user
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CarSuv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'CarSuv.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'car_suv',
        'USER': "root",
        'PASSWORD': '123456',
        'HOST': "localhost",
        'port': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

AUTH_USER_MODEL = "KeShiHua.Users"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'images'),
]



USE_I18N = True
USE_L10N = True
USE_TZ = True
STATIC_URL = '/static/'
SIMPLEUI_INDEX = 'http://127.0.0.1:8000/admin'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_DEFAULT_THEME = 'layui.css'
SIMPLEUI_LOGO = 'https://static.vecteezy.com/system/resources/previews/009/013/567/original/suv-car-illustration-logo-vector.jpg'


ACCONUT_AUTHENTICATION_METHOD = 'username_email' #可以使用用户名和邮箱登录
# ACCONUT_EMAIL_REQUIRED = True
ACCONUT_EMAIL_VERIFICATION = 'none' #是否强制邮箱验证optional是可选 none是否

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/index' #登录成功后跳转
ACCONUT_LOGOUT_REDIRECT_URL = '/index' #退出登录后跳转

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
ACCOUNT_EMAIL_REQUIRED = False
EMAIL_HOST = 'smtp.qq.com' #
EMAIL_PORT = 465
EMAIL_HOST_USER = '2691034920@qq.com'  # 或者'
EMAIL_HOST_PASSWORD = 'yglqfzsjjtxbdgea'  #邮箱授权码
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = '2691034920@qq.com'
ACCOUNT_LOGOUT_ON_GET = True

