# Generated by Django 4.1 on 2024-12-08 09:31

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(default='', max_length=124, verbose_name='名字')),
                ('car_price', models.CharField(default='', max_length=51, verbose_name='价格')),
                ('car_num', models.CharField(default='', max_length=51, verbose_name='销量')),
                ('car_img', models.CharField(default='', max_length=51, verbose_name='图片')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '车辆信息表',
                'verbose_name_plural': '车辆信息表',
            },
        ),
        migrations.CreateModel(
            name='XinXi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=124, verbose_name='标题')),
                ('img', models.CharField(default='', max_length=1024, verbose_name='图片链接')),
                ('region', models.CharField(default='', max_length=51, verbose_name='区域')),
                ('direction', models.CharField(default='', max_length=51, verbose_name='朝向')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('mianji', models.FloatField(default=0.0, verbose_name='面积')),
                ('huxing', models.CharField(default='', max_length=52, verbose_name='户型')),
                ('louceng', models.FloatField(default=0.0, verbose_name='楼层')),
                ('all_louceng', models.FloatField(default=0.0, verbose_name='总层数')),
                ('mingcheng', models.CharField(default='', max_length=52, verbose_name='小区名称')),
                ('lianjie', models.CharField(default='', max_length=1024, verbose_name='链接')),
                ('city', models.CharField(default='', max_length=52, verbose_name='市区')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '信息表',
                'verbose_name_plural': '信息表',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.CharField(default='18', max_length=16, verbose_name='年龄')),
                ('set', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=12, verbose_name='性别')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
