# Generated by Django 4.1 on 2024-12-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='max_price',
            field=models.CharField(default='', max_length=51, verbose_name='最高价格'),
        ),
        migrations.AddField(
            model_name='info',
            name='min_price',
            field=models.CharField(default='', max_length=51, verbose_name='最低价格'),
        ),
    ]
