# Generated by Django 4.1 on 2024-12-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0002_info_max_price_info_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='year',
            field=models.CharField(default='', max_length=124, verbose_name='名字'),
        ),
    ]
