# Generated by Django 4.1 on 2024-12-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0003_info_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='year',
            new_name='car_year',
        ),
    ]
