# Generated by Django 4.1 on 2024-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0004_rename_year_info_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='car_img',
            field=models.CharField(default='', max_length=500, verbose_name='图片'),
        ),
    ]
