# Generated by Django 4.1 on 2024-12-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0005_alter_info_car_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='car_sale',
            field=models.CharField(default='', max_length=124, verbose_name='是否在售'),
        ),
        migrations.AlterField(
            model_name='info',
            name='car_year',
            field=models.CharField(default='', max_length=124, verbose_name='年份'),
        ),
    ]
