# Generated by Django 4.1 on 2024-12-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0006_info_car_sale_alter_info_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='car_num',
            field=models.IntegerField(default='', max_length=51, verbose_name='销量'),
        ),
    ]
