# Generated by Django 4.1 on 2024-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0007_alter_info_car_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='car_num',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='info',
            name='max_price',
            field=models.FloatField(default='', verbose_name='最高价格'),
        ),
        migrations.AlterField(
            model_name='info',
            name='min_price',
            field=models.FloatField(default='', verbose_name='最低价格'),
        ),
    ]
