# Generated by Django 3.1.2 on 2025-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='brand',
            field=models.CharField(default='', max_length=124, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='info',
            name='car_num_std',
            field=models.FloatField(default=0.0, null=True, verbose_name='标准化销量'),
        ),
        migrations.AddField(
            model_name='info',
            name='cluster',
            field=models.IntegerField(default=0, null=True, verbose_name='聚类结果'),
        ),
        migrations.AddField(
            model_name='info',
            name='max_price_norm',
            field=models.FloatField(default=0.0, null=True, verbose_name='归一化最高价格'),
        ),
        migrations.AddField(
            model_name='info',
            name='min_price_norm',
            field=models.FloatField(default=0.0, null=True, verbose_name='归一化最低价格'),
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
