# Generated by Django 3.1.2 on 2025-05-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeShiHua', '0008_alter_info_car_num_alter_info_max_price_and_more'),
        ('KeShiHua', '0009_auto_20250521_0014'),
    ]

    operations = [
    ]
